alias gtd="cd ~/Downloads/"
alias t="gnome-terminal"
alias c="vagrant halt && vagrant up && vagrant ssh"
alias clip="xsel --clipboard"
alias intellij="/home/trevor/idea-IU-135.480/bin/idea.sh &"
alias t='gnome-terminal &'
alias gtm='cd ~/Media/Video/Movies'
alias gtt='cd ~/Media/Video/TV'
alias fnv="~/bin/findAndVim"
alias wnv="~/bin/whichAndVim"
alias v="gvim -v"
alias pythonc="python -m py_compile"
alias tm="tmux -2"
alias cmkdir="mkdir $1; cd $_"
